src/account/urls.py
from django.contrib import admin
from django.urls import path

from account.views import SignUp, UserCreate, ContactForm, MyProfile, SignUpView, Activate

app_name = 'account'

urlpatterns = [
    # path('signup/', SignUp.as_view(), name='signup'),
    path('registration/', UserCreate.as_view(), name='registration'),
    path('contact/', ContactForm.as_view(), name='contact'),
    path('profile/<int:pk>/', MyProfile.as_view(), name='profile'),
    path('signup', SignUpView.as_view(), name='signup'),
    path('activate/<int:pk>', Activate.as_view(), name='activate'),
]

src/currency/urls.py
from django.contrib import admin
from django.urls import path

from currency.views import RateListView, RateCSV, LatestRates

app_name = 'currency'

urlpatterns = [
    path('rates/', RateListView.as_view(), name='rates'),
    path('latest-rates/', LatestRates.as_view(), name='latest-rates'),
    path('download/rates/', RateCSV.as_view(), name='download-rates'),
]

src/currency_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from django.views.generic.base import TemplateView

from rest_framework_swagger.views import get_swagger_view
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

API_PREFIX = 'api/v1'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),

    path('currency/', include('currency.urls')),
    path('account/', include('account.urls')),

    # API
    path(f'{API_PREFIX}/currency/', include('currency.api.urls')),
    path(f'{API_PREFIX}/account/', include('account.api.urls')),

    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]
# SWAGGER
schema_view = get_swagger_view(title='DOCS')

urlpatterns.append(path(f'{API_PREFIX}/docs/', schema_view))

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
  {% load compress %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

{% compress css %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'landing/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
  <link href="{% static 'landing/css/resume.min.css' %}" rel="stylesheet">
{% endcompress %}
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{% static 'landing/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
      <span class="d-block d-lg-none">{{ request.user.get_full_name }}</span>
      {% if user.is_authenticated and request.user.avatar %}
      <span class="d-none d-lg-block">
        <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{ request.user.avatar.url }}" alt="">
      </span>
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:profile' user.id %}">My profile</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'account:signup' %}">SignUp</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'currency:rates' %}">Rates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'currency:download-rates' %}">Download Rates</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'account:contact' %}">Contact Form</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid p-0">
    {% block content %}
    {% endblock %}

  </div>
{% compress js %}
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'landing/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'landing/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'landing/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'landing/js/resume.min.js' %}"></script>
{% endcompress %}
</body>

</html>

src/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="about">
    <div class="w-100">
        <h1 class="mb-0">Artur
            <span class="text-primary">Chesnokov</span>
        </h1>
        <div class="subheading mb-5">49127 Dnipro · Ukraine ·
            <a href="mailto:artur.chesnokov@email.com">artur.chesnokov@email.com</a>
        </div>
        <p class="lead mb-5">Currency rate service was created during studying on the Python courses in Hillel IT school.</p>
        <div class="social-icons">
            <a href="https://www.linkedin.com/in/artur-chesnokov" target="_blank">
                <i class="fab fa-linkedin-in"></i>
            </a>
            <a href="https://github.com/arturchesnokov" target="_blank">
                <i class="fab fa-github"></i>
            </a>
            <a href="https://www.facebook.com/artur.chesnokov.9" target="_blank">
                <i class="fab fa-facebook-f"></i>
            </a>
        </div>
    </div>
</section>
{% endblock %}

src/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
</div>
{% endblock %}